const globalActions = {
  FETCH_USER_PROFILE: 'GLOBAL/FETCH_USER_PROFILE',
  FETCH_USER_PROFILE_LOADING: 'GLOBAL/FETCH_USER_PROFILE_LOADING',
  FETCH_USER_PROFILE_SUCCESS: 'GLOBAL/FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILURE: 'GLOBAL/FETCH_USER_PROFILE_FAILURE',
  FETCH_USER_EXTRA_PROFILE: 'GLOBAL/FETCH_USER_EXTRA_PROFILE',
  FETCH_USER_EXTRA_PROFILE_LOADING: 'GLOBAL/FETCH_USER_EXTRA_PROFILE_LOADING',
  FETCH_USER_EXTRA_PROFILE_SUCCESS: 'GLOBAL/FETCH_USER_EXTRA_PROFILE_SUCCESS',
  FETCH_USER_EXTRA_PROFILE_FAILURE: 'GLOBAL/FETCH_USER_EXTRA_PROFILE_FAILURE',
};

export default globalActions;
